batch_size: 64
height: 32
learning_rate: 0.004
max_text_length: 21
model_path: AI/202402061644
train_epochs: 200
vocab: '!"#&''()*+,-./0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
width: 128
